// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Id from "rescript/lib/es6/belt_Id.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function cmp(a, b) {
  return Belt_Array.cmpU(a, b, Caml_obj.compare);
}

var ArrayCmp = Belt_Id.MakeComparableU({
      cmp: cmp
    });

export {
  ArrayCmp ,
}
/* ArrayCmp Not a pure module */
