// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function make() {
  return {
          dense: [],
          sparse: []
        };
}

function add(set, value) {
  set.sparse[value] = set.sparse.length;
  set.dense.push(value);
}

function has(set, value) {
  var index = set.sparse[value];
  if (index !== undefined) {
    return Caml_obj.equal(set.dense[index], value);
  } else {
    return false;
  }
}

function remove(set, value) {
  if (!has(set, value)) {
    return ;
  }
  var swap = set.dense.pop();
  if (!Caml_obj.notequal(swap, value)) {
    return ;
  }
  var swapValue = Core__Option.getExn(swap, undefined);
  set.dense[set.sparse[value]] = swapValue;
  set.sparse[swapValue] = set.sparse[value];
}

export {
  make ,
  add ,
  has ,
  remove ,
}
/* No side effect */
