// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as Belt_MutableMap from "rescript/lib/es6/belt_MutableMap.js";
import * as Component_ArrayCmp from "./Component_ArrayCmp.res.js";

function make() {
  return {
          dt: 0,
          startupSystems: [],
          renderSystems: [],
          updateSystems: [],
          entityToComponentStorage: new Map(),
          componentIdToArchetypeSet: new Map(),
          componentIdsToArchetype: Belt_MutableMap.make(Component_ArrayCmp.ArrayCmp),
          componentIdCounter: 0,
          entityIdCounter: 0
        };
}

function callSystems(world, systems) {
  for(var i = 0 ,i_finish = systems.length; i < i_finish; ++i){
    systems[i](world);
  }
}

function startup(world) {
  callSystems(world, world.startupSystems);
}

function update(world, dt) {
  world.dt = dt;
  callSystems(world, world.updateSystems);
}

function render(world) {
  callSystems(world, world.renderSystems);
}

function registerSystem(world, phase, system) {
  var arrayToPush;
  switch (phase) {
    case "Startup" :
        arrayToPush = world.startupSystems;
        break;
    case "Render" :
        arrayToPush = world.renderSystems;
        break;
    case "Update" :
        arrayToPush = world.updateSystems;
        break;
    
  }
  arrayToPush.push(system);
}

function removeSystem(world, phase, system) {
  var arrayToRemove;
  switch (phase) {
    case "Startup" :
        arrayToRemove = world.startupSystems;
        break;
    case "Render" :
        arrayToRemove = world.renderSystems;
        break;
    case "Update" :
        arrayToRemove = world.updateSystems;
        break;
    
  }
  var maybeIndex = Core__Array.indexOfOpt(arrayToRemove, system);
  if (Core__Option.isSome(maybeIndex)) {
    arrayToRemove.splice(Core__Option.getExn(maybeIndex, undefined), 1);
    return ;
  }
  
}

function hasComponent(world, entity, componentId) {
  var match = world.entityToComponentStorage.get(entity);
  if (match === undefined) {
    return false;
  }
  var archetypeSet = world.componentIdToArchetypeSet.get(componentId);
  if (archetypeSet !== undefined) {
    return Caml_option.valFromOption(archetypeSet).has(match.archetype.id);
  } else {
    return false;
  }
}

function getComponent(world, entity, componentId) {
  var match = world.entityToComponentStorage.get(entity);
  if (match === undefined) {
    return ;
  }
  var components = match.archetype.componentIdToStorage.get(componentId);
  if (components !== undefined) {
    return components[match.index];
  }
  
}

function defineComponent(world) {
  world.componentIdCounter = world.componentIdCounter + 1 | 0;
  return world.componentIdCounter;
}

function makeEntity(world) {
  world.entityIdCounter = world.entityIdCounter + 1 | 0;
  return world.entityIdCounter;
}

function hasEntity(world, entity) {
  return world.entityIdCounter <= entity;
}

export {
  make ,
  startup ,
  update ,
  render ,
  registerSystem ,
  removeSystem ,
  hasComponent ,
  getComponent ,
  defineComponent ,
  makeEntity ,
  hasEntity ,
}
/* Component_ArrayCmp Not a pure module */
