// Generated by ReScript, PLEASE EDIT WITH CARE


function make() {
  return {
          dt: 0,
          renderSystems: [],
          updateSystems: []
        };
}

function update(world, dt) {
  world.dt = dt;
  var systems = world.updateSystems;
  for(var i = 0 ,i_finish = systems.length; i < i_finish; ++i){
    systems[i](world);
  }
}

function render(world) {
  var systems = world.renderSystems;
  for(var i = 0 ,i_finish = systems.length; i < i_finish; ++i){
    systems[i](world);
  }
}

function registerSystem(world, priority, system) {
  var arrayToPush;
  arrayToPush = priority === "Render" ? world.renderSystems : world.updateSystems;
  arrayToPush.push(system);
}

export {
  make ,
  update ,
  render ,
  registerSystem ,
}
/* No side effect */
