// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";

function make() {
  return Js_exn.raiseError("E:\\dev\\scatter\\src\\engine\\2d\\Sprite.res:4:51-56 - Todo");
}

export {
  make ,
}
/* No side effect */
